version: '3.8'

services:
  gitlab_bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - ALLOWED_EVENTS=${ALLOWED_EVENTS}
      - FLASK_ENV=production
    restart: always
    volumes:
      - ./logs:/app/logs
